As the initial step, import the required libraries that we require to perform the tasks like preprocessing, training our model and predicting the accuracy score of our model

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,precision_score,recall_score,f1_score

Import the dataset to the simulation software and to view the first 5 rows of our dataset we used head function in pandas dataframe

In [2]:
df=pd.read_csv("/content/drive/MyDrive/aquaponics/IoTPond11.csv")
df.head()

created_at  entry_id  TEMPERATURE  TURBIDITY  DISOLVED OXYGEN  \
0  2021-06-25 15:14:07 CET         1      27.0625        100           22.562   
1  2021-06-25 15:14:26 CET         2      27.1250        100           20.493   
2  2021-06-25 15:15:42 CET         3      27.1250        100           12.555   
3  2021-06-25 15:16:01 CET         4      27.0625        100           17.403   
4  2021-06-25 15:16:21 CET         5      27.1250        100           22.765   

        pH      AMMONIA  NITRATE  Population  Lenght  Weight  
0  8.20213  12151.86328     1061          50   14.12    33.8  
1  8.19759  15100.59473     1050          50   14.12    33.8  
2  8.20213  42010.77344     1039          50   14.12    33.8  
3  8.19759  21075.64453     1037          50   14.12    33.8  
4  8.21121  62079.92578     1039          50   14.12    33.8

In [3]:
df.describe()

entry_id  TEMPERATURE    TURBIDITY  DISOLVED OXYGEN           pH  \
count  3165.000000  3165.000000  3165.000000      3165.000000  3165.000000   
mean   1583.000000    24.415166    89.360821         4.560476     6.523293   
std     913.801127    15.807021    25.081863         5.702163     2.034633   
min       1.000000  -127.000000   -95.000000         0.000000     1.288530   
25%     792.000000    25.437500   100.000000         0.000000     7.230690   
50%    1583.000000    26.125000   100.000000         1.293000     7.239770   
75%    2374.000000    26.812500   100.000000         8.361000     7.244310   
max    3165.000000    27.375000   100.000000        33.917000    15.451660   

            AMMONIA      NITRATE  Population       Lenght       Weight  
count  3.164000e+03  3165.000000      3165.0  3165.000000  3165.000000  
mean   6.118588e+08   583.723223        50.0    36.992305   513.557858  
std    1.373474e+10   226.325204         0.0    10.938499   247.249547  
min    0.000000e+00     0.000000        50.0    14.120000    33.800000  
25%    0.000000e+00   576.000000        50.0    41.957860   625.885700  
50%    0.000000e+00   624.000000        50.0    41.957860   625.885700  
75%    1.775144e+03   654.000000        50.0    42.969290   644.357100  
max    4.270000e+11  2165.000000        50.0    44.650000   701.000000

To check for the null values present in our dataset we use isnull() function


In [4]:
df.isnull().sum()

created_at         0
entry_id           0
TEMPERATURE        0
TURBIDITY          0
DISOLVED OXYGEN    0
pH                 0
AMMONIA            1
NITRATE            0
Population         0
Lenght             0
Weight             0
dtype: int64

Null Values to be filled with mean values

In [5]:
df=df.fillna(df.mean())

<ipython-input-5-6f8c6f28e805>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df=df.fillna(df.mean())


Checking if the numbers are within limits are having infinite

In [6]:
df.isin([np.inf,-np.inf]).sum()

created_at         0
entry_id           0
TEMPERATURE        0
TURBIDITY          0
DISOLVED OXYGEN    0
pH                 0
AMMONIA            0
NITRATE            0
Population         0
Lenght             0
Weight             0
dtype: int64

Drop all the unnecessary columns from the dataset

In [7]:
df=df.drop(columns='entry_id')
df=df.drop(columns='Population')
df=df.drop(columns='created_at')

Check the datatype of each columns in our dataset

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3165 entries, 0 to 3164
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   TEMPERATURE      3165 non-null   float64
 1   TURBIDITY        3165 non-null   int64  
 2   DISOLVED OXYGEN  3165 non-null   float64
 3   pH               3165 non-null   float64
 4   AMMONIA          3165 non-null   float64
 5   NITRATE          3165 non-null   int64  
 6   Lenght           3165 non-null   float64
 7   Weight           3165 non-null   float64
dtypes: float64(6), int64(2)
memory usage: 197.9 KB


We see that our classifications labels fish_length and fish_weight are in float variables and we need to convert them to string.

In [10]:
df=df.astype({"Lenght":'str',"Weight":'str'})

To find the corelation between the input variables

In [11]:
df.corr()

TEMPERATURE  TURBIDITY  DISOLVED OXYGEN        pH   AMMONIA  \
TEMPERATURE         1.000000   0.433754         0.110461 -0.468328  0.003370   
TURBIDITY           0.433754   1.000000        -0.201478  0.475919  0.018905   
DISOLVED OXYGEN     0.110461  -0.201478         1.000000 -0.279255 -0.023504   
pH                 -0.468328   0.475919        -0.279255  1.000000  0.016190   
AMMONIA             0.003370   0.018905        -0.023504  0.016190  1.000000   
NITRATE             0.246943   0.716135        -0.124153  0.570198  0.014826   

                  NITRATE  
TEMPERATURE      0.246943  
TURBIDITY        0.716135  
DISOLVED OXYGEN -0.124153  
pH               0.570198  
AMMONIA          0.014826  
NITRATE          1.000000

In [12]:
x=df.drop(columns=['Lenght','Weight'])
y=df.drop(columns=['TEMPERATURE','TURBIDITY','DISOLVED OXYGEN','pH','AMMONIA','NITRATE'])
y1=y['Lenght']
y2=y['Weight']

Y1 corresponds to the model for fish length label and Y2 corresponds to the model for fish weight label. Splitting the data for training and testing


In [13]:
X_train,X_test,Y1_train,Y1_test=train_test_split(x,y1,test_size=0.2,random_state=0)
X_train,X_test,Y2_train,Y2_test=train_test_split(x,y2,test_size=0.2,random_state=0)

Saling of input data

In [14]:
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

1) Logistic Regression

In [15]:
model=LogisticRegression(multi_class='multinomial')
data=model.fit(X_train,Y1_train)
Y1_predict=data.predict(X_test)
print("The classification report for Fish Length is:",classification_report(Y1_test,Y1_predict))
print("The confusion matrix for Fish Length is:",confusion_matrix(Y1_test,Y1_predict))
data=model.fit(X_train,Y2_train)
Y2_predict=data.predict(X_test)
print("The classification report for Fish Weight is:",classification_report(Y2_test,Y2_predict))
print("The confusion matrix for Fish Weight is:",confusion_matrix(Y2_test,Y2_predict))

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with n

The classification report for Fish Length is:               precision    recall  f1-score   support

       14.12       0.00      0.00      0.00         8
 15.37142856       0.00      0.00      0.00        57
  15.6842857       0.00      0.00      0.00        58
       32.46       0.59      0.31      0.41        32
    33.04286       0.00      0.00      0.00         1
    41.95786       0.58      1.00      0.74       288
    42.96929       0.33      0.03      0.05        71
       44.65       1.00      0.97      0.99       118

    accuracy                           0.66       633
   macro avg       0.31      0.29      0.27       633
weighted avg       0.52      0.66      0.55       633

The confusion matrix for Fish Length is: [[  0   0   0   7   0   1   0   0]
 [  0   0   0   0   0  57   0   0]
 [  0   0   0   0   0  55   3   0]
 [  0   0   0  10   0  21   1   0]
 [  0   0   0   0   0   1   0   0]
 [  0   0   0   0   0 288   0   0]
 [  0   0   1   0   0  68   2   0]
 [  0   0   0   0

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with n

2) Decision Tree Classifier

In [16]:
model=DecisionTreeClassifier()
data=model.fit(X_train,Y1_train)
Y1_predict=data.predict(X_test)
print("The classification report for Fish Length is:",classification_report(Y1_test,Y1_predict))
print("The confusion matrix for Fish Length is:",confusion_matrix(Y1_test,Y1_predict))
data=model.fit(X_train,Y2_train)
Y2_predict=data.predict(X_test)
print("The classification report for Fish Weight is:",classification_report(Y2_test,Y2_predict))
print("The confusion matrix for Fish Weight is:",confusion_matrix(Y2_test,Y2_predict))

The classification report for Fish Length is:               precision    recall  f1-score   support

       14.12       0.00      0.00      0.00         8
 15.37142856       0.11      0.18      0.14        57
  15.6842857       0.11      0.12      0.11        58
       32.46       0.74      0.72      0.73        32
    33.04286       1.00      1.00      1.00         1
    41.95786       0.81      0.72      0.76       288
    42.96929       0.21      0.20      0.20        71
       44.65       1.00      0.99      1.00       118

    accuracy                           0.60       633
   macro avg       0.50      0.49      0.49       633
weighted avg       0.64      0.60      0.62       633

The confusion matrix for Fish Length is: [[  0   0   0   8   0   0   0   0]
 [  0  10   0   0   0  47   0   0]
 [  0   0   7   0   0   0  51   0]
 [  9   0   0  23   0   0   0   0]
 [  0   0   0   0   1   0   0   0]
 [  0  79   1   0   0 207   1   0]
 [  0   0  57   0   0   0  14   0]
 [  0   0   1   0

3) Support Vector Machine

In [17]:
model=SVC()
data=model.fit(X_train,Y1_train)
Y1_predict=data.predict(X_test)
print("The classification report for Fish Length is:",classification_report(Y1_test,Y1_predict))
print("The confusion matrix for Fish Length is:",confusion_matrix(Y1_test,Y1_predict))
data=model.fit(X_train,Y2_train)
Y2_predict=data.predict(X_test)
print("The classification report for Fish Weight is:",classification_report(Y2_test,Y2_predict))
print("The confusion matrix for Fish Weight is:",confusion_matrix(Y2_test,Y2_predict))

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


The classification report for Fish Length is:               precision    recall  f1-score   support

       14.12       0.00      0.00      0.00         8
 15.37142856       0.00      0.00      0.00        57
  15.6842857       0.00      0.00      0.00        58
       32.46       0.75      0.94      0.83        32
    33.04286       0.00      0.00      0.00         1
    41.95786       0.62      1.00      0.76       288
    42.96929       0.33      0.03      0.05        71
       44.65       1.00      1.00      1.00       118

    accuracy                           0.69       633
   macro avg       0.34      0.37      0.33       633
weighted avg       0.54      0.69      0.58       633

The confusion matrix for Fish Length is: [[  0   0   0   8   0   0   0   0]
 [  0   0   0   0   0  57   0   0]
 [  0   0   0   1   0  55   2   0]
 [  0   0   0  30   0   0   2   0]
 [  0   0   0   0   0   1   0   0]
 [  0   0   0   0   0 288   0   0]
 [  0   0   1   1   0  67   2   0]
 [  0   0   0   0

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


4) Random Forest Classifier

In [18]:
model=RandomForestClassifier()
data=model.fit(X_train,Y1_train)
Y1_predict=data.predict(X_test)
print("The classification report for Fish Length is:",classification_report(Y1_test,Y1_predict))
print("The confusion matrix for Fish Length is:",confusion_matrix(Y1_test,Y1_predict))
data=model.fit(X_train,Y2_train)
Y2_predict=data.predict(X_test)
print("The classification report for Fish Weight is:",classification_report(Y2_test,Y2_predict))
print("The confusion matrix for Fish Weight is:",confusion_matrix(Y2_test,Y2_predict))

The classification report for Fish Length is:               precision    recall  f1-score   support

       14.12       0.09      0.12      0.11         8
 15.37142856       0.06      0.07      0.07        57
  15.6842857       0.04      0.03      0.04        58
       32.46       0.76      0.69      0.72        32
    33.04286       1.00      1.00      1.00         1
    41.95786       0.80      0.78      0.79       288
    42.96929       0.27      0.30      0.28        71
       44.65       1.00      1.00      1.00       118

    accuracy                           0.62       633
   macro avg       0.50      0.50      0.50       633
weighted avg       0.63      0.62      0.63       633

The confusion matrix for Fish Length is: [[  1   0   0   7   0   0   0   0]
 [  0   4   0   0   0  53   0   0]
 [  0   0   2   0   0   1  55   0]
 [ 10   0   0  22   0   0   0   0]
 [  0   0   0   0   1   0   0   0]
 [  0  61   0   0   0 226   1   0]
 [  0   0  49   0   0   1  21   0]
 [  0   0   0   0

5) K Nearest Neighbors

In [19]:
model=KNeighborsClassifier()
data=model.fit(X_train,Y1_train)
Y1_predict=data.predict(X_test)
print("The classification report for Fish Length is:",classification_report(Y1_test,Y1_predict))
print("The confusion matrix for Fish Length is:",confusion_matrix(Y1_test,Y1_predict))
data=model.fit(X_train,Y2_train)
Y2_predict=data.predict(X_test)
print("The classification report for Fish Weight is:",classification_report(Y2_test,Y2_predict))
print("The confusion matrix for Fish Weight is:",confusion_matrix(Y2_test,Y2_predict))

The classification report for Fish Length is:               precision    recall  f1-score   support

       14.12       0.50      0.25      0.33         8
 15.37142856       0.14      0.14      0.14        57
  15.6842857       0.14      0.09      0.11        58
       32.46       0.83      0.91      0.87        32
    33.04286       0.00      0.00      0.00         1
    41.95786       0.80      0.86      0.83       288
    42.96929       0.33      0.34      0.33        71
       44.65       1.00      1.00      1.00       118

    accuracy                           0.68       633
   macro avg       0.47      0.45      0.45       633
weighted avg       0.66      0.68      0.67       633

The confusion matrix for Fish Length is: [[  2   0   0   6   0   0   0   0]
 [  0   8   2   0   0  47   0   0]
 [  0   1   5   0   0   3  49   0]
 [  2   0   1  29   0   0   0   0]
 [  0   1   0   0   0   0   0   0]
 [  0  40   1   0   0 247   0   0]
 [  0   7  28   0   0  12  24   0]
 [  0   0   0   0

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classificat

6) Ada Boost Classifier

In [20]:
model=AdaBoostClassifier()
data=model.fit(X_train,Y1_train)
Y1_predict=data.predict(X_test)
print("The classification report for Fish Length is:",classification_report(Y1_test,Y1_predict))
print("The confusion matrix for Fish Length is:",confusion_matrix(Y1_test,Y1_predict))
data=model.fit(X_train,Y2_train)
Y2_predict=data.predict(X_test)
print("The classification report for Fish Weight is:",classification_report(Y2_test,Y2_predict))
print("The confusion matrix for Fish Weight is:",confusion_matrix(Y2_test,Y2_predict))

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


The classification report for Fish Length is:               precision    recall  f1-score   support

       14.12       0.00      0.00      0.00         8
 15.37142856       0.00      0.00      0.00        57
  15.6842857       0.00      0.00      0.00        58
       32.46       0.00      0.00      0.00        32
    33.04286       0.00      0.00      0.00         1
    41.95786       0.56      1.00      0.72       288
    42.96929       0.00      0.00      0.00        71
       44.65       1.00      1.00      1.00       118

    accuracy                           0.64       633
   macro avg       0.19      0.25      0.21       633
weighted avg       0.44      0.64      0.51       633

The confusion matrix for Fish Length is: [[  0   0   0   0   0   8   0   0]
 [  0   0   0   0   0  57   0   0]
 [  0   0   0   0   0  58   0   0]
 [  0   0   0   0   0  32   0   0]
 [  0   0   0   0   0   1   0   0]
 [  0   0   0   0   0 288   0   0]
 [  0   0   0   0   0  71   0   0]
 [  0   0   0   0

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


7) Extra Trees Classifier

In [21]:
model=ExtraTreesClassifier()
data=model.fit(X_train,Y1_train)
Y1_predict=data.predict(X_test)
print("The classification report for Fish Length is:",classification_report(Y1_test,Y1_predict))
print("The confusion matrix for Fish Length is:",confusion_matrix(Y1_test,Y1_predict))
data=model.fit(X_train,Y2_train)
Y2_predict=data.predict(X_test)
print("The classification report for Fish Weight is:",classification_report(Y2_test,Y2_predict))
print("The confusion matrix for Fish Weight is:",confusion_matrix(Y2_test,Y2_predict))

The classification report for Fish Length is:               precision    recall  f1-score   support

       14.12       0.00      0.00      0.00         8
 15.37142856       0.07      0.09      0.08        57
  15.6842857       0.02      0.02      0.02        58
       32.46       0.74      0.72      0.73        32
    33.04286       1.00      1.00      1.00         1
    41.95786       0.80      0.76      0.78       288
    42.96929       0.26      0.28      0.27        71
       44.65       1.00      1.00      1.00       118

    accuracy                           0.61       633
   macro avg       0.49      0.48      0.48       633
weighted avg       0.63      0.61      0.62       633

The confusion matrix for Fish Length is: [[  0   0   0   8   0   0   0   0]
 [  0   5   0   0   0  52   0   0]
 [  0   0   1   0   0   1  56   0]
 [  9   0   0  23   0   0   0   0]
 [  0   0   0   0   1   0   0   0]
 [  0  68   0   0   0 219   1   0]
 [  0   0  49   0   0   2  20   0]
 [  0   0   0   0

8) Gradient Boosting Classifier

In [22]:
model=GradientBoostingClassifier()
data=model.fit(X_train,Y1_train)
Y1_predict=data.predict(X_test)
print("The classification report for Fish Length is:",classification_report(Y1_test,Y1_predict))
print("The confusion matrix for Fish Length is:",confusion_matrix(Y1_test,Y1_predict))
data=model.fit(X_train,Y2_train)
Y2_predict=data.predict(X_test)
print("The classification report for Fish Weight is:",classification_report(Y2_test,Y2_predict))
print("The confusion matrix for Fish Weight is:",confusion_matrix(Y2_test,Y2_predict))

The classification report for Fish Length is:               precision    recall  f1-score   support

       14.12       0.00      0.00      0.00         8
 15.37142856       0.18      0.16      0.17        57
  15.6842857       0.08      0.05      0.06        58
       32.46       0.74      0.72      0.73        32
    33.04286       1.00      1.00      1.00         1
    41.95786       0.83      0.86      0.84       288
    42.96929       0.38      0.48      0.42        71
       44.65       1.00      0.99      1.00       118

    accuracy                           0.69       633
   macro avg       0.53      0.53      0.53       633
weighted avg       0.67      0.69      0.68       633

The confusion matrix for Fish Length is: [[  0   0   0   8   0   0   0   0]
 [  0   9   0   0   0  48   0   0]
 [  0   0   3   0   0   1  54   0]
 [  9   0   0  23   0   0   0   0]
 [  0   0   0   0   1   0   0   0]
 [  0  41   0   0   0 247   0   0]
 [  0   0  36   0   0   1  34   0]
 [  0   0   0   0

9) Naive Bayes Classifier

In [23]:
model=MultinomialNB()
data=model.fit(X_train,Y1_train)
Y1_predict=data.predict(X_test)
print("The classification report for Fish Length is:",classification_report(Y1_test,Y1_predict))
print("The confusion matrix for Fish Length is:",confusion_matrix(Y1_test,Y1_predict))
data=model.fit(X_train,Y2_train)
Y2_predict=data.predict(X_test)
print("The classification report for Fish Weight is:",classification_report(Y2_test,Y2_predict))
print("The confusion matrix for Fish Weight is:",confusion_matrix(Y2_test,Y2_predict))

The classification report for Fish Length is:               precision    recall  f1-score   support

       14.12       0.00      0.00      0.00         8
 15.37142856       0.00      0.00      0.00        57
  15.6842857       0.00      0.00      0.00        58
       32.46       0.00      0.00      0.00        32
    33.04286       0.00      0.00      0.00         1
    41.95786       0.45      1.00      0.63       288
    42.96929       0.00      0.00      0.00        71
       44.65       0.00      0.00      0.00       118

    accuracy                           0.45       633
   macro avg       0.06      0.12      0.08       633
weighted avg       0.21      0.45      0.28       633

The confusion matrix for Fish Length is: [[  0   0   0   0   0   8   0   0]
 [  0   0   0   0   0  57   0   0]
 [  0   0   0   0   0  58   0   0]
 [  0   0   0   0   0  32   0   0]
 [  0   0   0   0   0   1   0   0]
 [  0   0   0   0   0 288   0   0]
 [  0   0   0   0   0  71   0   0]
 [  0   0   0   0

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classificat