As the initial step, import the required libraries that we require to perform the tasks like preprocessing, training our model and predicting the accuracy score of our model

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,precision_score,recall_score,f1_score

Import the dataset to the simulation software and to view the first 5 rows of our dataset we used head function in pandas dataframe

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/aquaponics/IoTPond12.csv")
df.head()

In [ ]:
df.describe()

To check for the null values present in our dataset we use isnull() function


In [ ]:
df.isnull().sum()

created_at         0
entry_id           0
TEMPERATURE        0
TURBIDITY          0
DISOLVED OXYGEN    0
pH                 0
AMMONIA            1
NITRATE            0
Population         0
Lenght             0
Weight             0
dtype: int64

Null Values to be filled with mean values

In [3]:
df=df.fillna(df.mean())

<ipython-input-3-6f8c6f28e805>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df=df.fillna(df.mean())


Checking if the numbers are within limits are having infinite

In [4]:
df.isin([np.inf,-np.inf]).sum()

created_at         0
entry_id           0
TEMPERATURE        0
TURBIDITY          0
DISOLVED OXYGEN    0
pH                 0
AMMONIA            0
NITRATE            0
Population         0
Length             0
Weight             0
dtype: int64

Drop all the unnecessary columns from the dataset

In [5]:
df=df.drop(columns='entry_id')
df=df.drop(columns='Population')
df=df.drop(columns='created_at')

Check the datatype of each columns in our dataset

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3590 entries, 0 to 3589
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   TEMPERATURE      3590 non-null   float64
 1   TURBIDITY        3590 non-null   int64  
 2   DISOLVED OXYGEN  3590 non-null   float64
 3   pH               3590 non-null   float64
 4   AMMONIA          3590 non-null   float64
 5   NITRATE          3590 non-null   int64  
 6   Length           3590 non-null   float64
 7   Weight           3590 non-null   float64
dtypes: float64(6), int64(2)
memory usage: 224.5 KB


We see that our classifications labels fish_length and fish_weight are in float variables and we need to convert them to string.

In [7]:
df=df.astype({"Length":'str',"Weight":'str'})

To find the corelation between the input variables

In [8]:
df.corr()

TEMPERATURE  TURBIDITY  DISOLVED OXYGEN        pH   AMMONIA  \
TEMPERATURE         1.000000  -0.079386        -0.033957  0.073850  0.001629   
TURBIDITY          -0.079386   1.000000        -0.349424  0.004841 -0.002956   
DISOLVED OXYGEN    -0.033957  -0.349424         1.000000 -0.531587  0.009256   
pH                  0.073850   0.004841        -0.531587  1.000000 -0.003798   
AMMONIA             0.001629  -0.002956         0.009256 -0.003798  1.000000   
NITRATE            -0.044413  -0.452604         0.584013 -0.592720  0.001413   

                  NITRATE  
TEMPERATURE     -0.044413  
TURBIDITY       -0.452604  
DISOLVED OXYGEN  0.584013  
pH              -0.592720  
AMMONIA          0.001413  
NITRATE          1.000000

In [10]:
x=df.drop(columns=['Length','Weight'])
y=df.drop(columns=['TEMPERATURE','TURBIDITY','DISOLVED OXYGEN','pH','AMMONIA','NITRATE'])
y1=y['Length']
y2=y['Weight']

Y1 corresponds to the model for fish length label and Y2 corresponds to the model for fish weight label. Splitting the data for training and testing


In [11]:
X_train,X_test,Y1_train,Y1_test=train_test_split(x,y1,test_size=0.2,random_state=0)
X_train,X_test,Y2_train,Y2_test=train_test_split(x,y2,test_size=0.2,random_state=0)

Saling of input data

In [12]:
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

1) Logistic Regression

In [13]:
model=LogisticRegression(multi_class='multinomial')
data=model.fit(X_train,Y1_train)
Y1_predict=data.predict(X_test)
print("The classification report for Fish Length is:",classification_report(Y1_test,Y1_predict))
print("The confusion matrix for Fish Length is:",confusion_matrix(Y1_test,Y1_predict))
data=model.fit(X_train,Y2_train)
Y2_predict=data.predict(X_test)
print("The classification report for Fish Weight is:",classification_report(Y2_test,Y2_predict))
print("The confusion matrix for Fish Weight is:",confusion_matrix(Y2_test,Y2_predict))

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with n

The classification report for Fish Length is:               precision    recall  f1-score   support

       14.64       0.00      0.00      0.00         8
       32.01       0.42      1.00      0.59         5
    32.58643       0.81      0.71      0.76       124
    39.95929       0.47      0.85      0.61       110
    40.06857       0.00      0.00      0.00        10
    40.73571       0.66      0.62      0.64        81
    41.00142       0.00      0.00      0.00        33
   41.267134       1.00      0.01      0.02       100
    41.39642       0.16      0.06      0.08       105
    41.66213       0.42      0.85      0.57       142

    accuracy                           0.51       718
   macro avg       0.39      0.41      0.33       718
weighted avg       0.54      0.51      0.43       718

The confusion matrix for Fish Length is: [[  0   7   1   0   0   0   0   0   0   0]
 [  0   5   0   0   0   0   0   0   0   0]
 [  0   0  88  33   0   0   0   0   1   2]
 [  0   0  10  93   0   3

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with n

2) Decision Tree Classifier

In [14]:
model=DecisionTreeClassifier()
data=model.fit(X_train,Y1_train)
Y1_predict=data.predict(X_test)
print("The classification report for Fish Length is:",classification_report(Y1_test,Y1_predict))
print("The confusion matrix for Fish Length is:",confusion_matrix(Y1_test,Y1_predict))
data=model.fit(X_train,Y2_train)
Y2_predict=data.predict(X_test)
print("The classification report for Fish Weight is:",classification_report(Y2_test,Y2_predict))
print("The confusion matrix for Fish Weight is:",confusion_matrix(Y2_test,Y2_predict))

The classification report for Fish Length is:               precision    recall  f1-score   support

       14.64       0.20      0.12      0.15         8
       32.01       0.12      0.20      0.15         5
    32.58643       0.99      1.00      1.00       124
    39.95929       0.90      0.85      0.88       110
    40.06857       0.89      0.80      0.84        10
    40.73571       0.90      0.85      0.87        81
    41.00142       0.82      0.82      0.82        33
   41.267134       0.94      0.99      0.97       100
    41.39642       0.90      0.91      0.91       105
    41.66213       0.92      0.94      0.93       142

    accuracy                           0.91       718
   macro avg       0.76      0.75      0.75       718
weighted avg       0.91      0.91      0.91       718

The confusion matrix for Fish Length is: [[  1   7   0   0   0   0   0   0   0   0]
 [  4   1   0   0   0   0   0   0   0   0]
 [  0   0 124   0   0   0   0   0   0   0]
 [  0   0   0  94   0   7

3) Support Vector Machine

In [15]:
model=SVC()
data=model.fit(X_train,Y1_train)
Y1_predict=data.predict(X_test)
print("The classification report for Fish Length is:",classification_report(Y1_test,Y1_predict))
print("The confusion matrix for Fish Length is:",confusion_matrix(Y1_test,Y1_predict))
data=model.fit(X_train,Y2_train)
Y2_predict=data.predict(X_test)
print("The classification report for Fish Weight is:",classification_report(Y2_test,Y2_predict))
print("The confusion matrix for Fish Weight is:",confusion_matrix(Y2_test,Y2_predict))

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


The classification report for Fish Length is:               precision    recall  f1-score   support

       14.64       0.00      0.00      0.00         8
       32.01       0.38      1.00      0.56         5
    32.58643       0.75      0.91      0.82       124
    39.95929       0.56      0.80      0.66       110
    40.06857       0.00      0.00      0.00        10
    40.73571       0.71      0.59      0.64        81
    41.00142       0.00      0.00      0.00        33
   41.267134       0.80      0.04      0.08       100
    41.39642       0.36      0.50      0.42       105
    41.66213       0.57      0.73      0.64       142

    accuracy                           0.58       718
   macro avg       0.41      0.46      0.38       718
weighted avg       0.57      0.58      0.52       718

The confusion matrix for Fish Length is: [[  0   8   0   0   0   0   0   0   0   0]
 [  0   5   0   0   0   0   0   0   0   0]
 [  0   0 113   7   0   1   0   0   1   2]
 [  0   0  17  88   0   0

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


4) Random Forest Classifier

In [16]:
model=RandomForestClassifier()
data=model.fit(X_train,Y1_train)
Y1_predict=data.predict(X_test)
print("The classification report for Fish Length is:",classification_report(Y1_test,Y1_predict))
print("The confusion matrix for Fish Length is:",confusion_matrix(Y1_test,Y1_predict))
data=model.fit(X_train,Y2_train)
Y2_predict=data.predict(X_test)
print("The classification report for Fish Weight is:",classification_report(Y2_test,Y2_predict))
print("The confusion matrix for Fish Weight is:",confusion_matrix(Y2_test,Y2_predict))

The classification report for Fish Length is:               precision    recall  f1-score   support

       14.64       0.00      0.00      0.00         8
       32.01       0.20      0.40      0.27         5
    32.58643       1.00      1.00      1.00       124
    39.95929       0.91      0.93      0.92       110
    40.06857       1.00      0.90      0.95        10
    40.73571       0.91      0.88      0.89        81
    41.00142       0.96      0.82      0.89        33
   41.267134       0.97      0.99      0.98       100
    41.39642       0.91      0.95      0.93       105
    41.66213       0.95      0.95      0.95       142

    accuracy                           0.93       718
   macro avg       0.78      0.78      0.78       718
weighted avg       0.93      0.93      0.93       718

The confusion matrix for Fish Length is: [[  0   8   0   0   0   0   0   0   0   0]
 [  3   2   0   0   0   0   0   0   0   0]
 [  0   0 124   0   0   0   0   0   0   0]
 [  0   0   0 102   0   6

5) K Nearest Neighbors

In [17]:
model=KNeighborsClassifier()
data=model.fit(X_train,Y1_train)
Y1_predict=data.predict(X_test)
print("The classification report for Fish Length is:",classification_report(Y1_test,Y1_predict))
print("The confusion matrix for Fish Length is:",confusion_matrix(Y1_test,Y1_predict))
data=model.fit(X_train,Y2_train)
Y2_predict=data.predict(X_test)
print("The classification report for Fish Weight is:",classification_report(Y2_test,Y2_predict))
print("The confusion matrix for Fish Weight is:",confusion_matrix(Y2_test,Y2_predict))

The classification report for Fish Length is:               precision    recall  f1-score   support

       14.64       0.25      0.12      0.17         8
       32.01       0.22      0.40      0.29         5
    32.58643       0.93      0.95      0.94       124
    39.95929       0.76      0.84      0.80       110
    40.06857       1.00      0.60      0.75        10
    40.73571       0.80      0.73      0.76        81
    41.00142       0.67      0.61      0.63        33
   41.267134       0.66      0.58      0.62       100
    41.39642       0.67      0.72      0.70       105
    41.66213       0.84      0.87      0.85       142

    accuracy                           0.77       718
   macro avg       0.68      0.64      0.65       718
weighted avg       0.77      0.77      0.77       718

The confusion matrix for Fish Length is: [[  1   7   0   0   0   0   0   0   0   0]
 [  3   2   0   0   0   0   0   0   0   0]
 [  0   0 118   5   0   0   0   0   1   0]
 [  0   0   2  92   0  10

6) Ada Boost Classifier

In [18]:
model=AdaBoostClassifier()
data=model.fit(X_train,Y1_train)
Y1_predict=data.predict(X_test)
print("The classification report for Fish Length is:",classification_report(Y1_test,Y1_predict))
print("The confusion matrix for Fish Length is:",confusion_matrix(Y1_test,Y1_predict))
data=model.fit(X_train,Y2_train)
Y2_predict=data.predict(X_test)
print("The classification report for Fish Weight is:",classification_report(Y2_test,Y2_predict))
print("The confusion matrix for Fish Weight is:",confusion_matrix(Y2_test,Y2_predict))

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


The classification report for Fish Length is:               precision    recall  f1-score   support

       14.64       0.00      0.00      0.00         8
       32.01       0.29      0.40      0.33         5
    32.58643       0.00      0.00      0.00       124
    39.95929       0.27      0.99      0.42       110
    40.06857       0.00      0.00      0.00        10
    40.73571       0.00      0.00      0.00        81
    41.00142       0.00      0.00      0.00        33
   41.267134       0.00      0.00      0.00       100
    41.39642       0.00      0.00      0.00       105
    41.66213       0.35      0.72      0.47       142

    accuracy                           0.30       718
   macro avg       0.09      0.21      0.12       718
weighted avg       0.11      0.30      0.16       718

The confusion matrix for Fish Length is: [[  0   5   3   0   0   0   0   0   0   0]
 [  0   2   3   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0 124]
 [  0   0   0 109   0   0

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


7) Extra Trees Classifier

In [19]:
model=ExtraTreesClassifier()
data=model.fit(X_train,Y1_train)
Y1_predict=data.predict(X_test)
print("The classification report for Fish Length is:",classification_report(Y1_test,Y1_predict))
print("The confusion matrix for Fish Length is:",confusion_matrix(Y1_test,Y1_predict))
data=model.fit(X_train,Y2_train)
Y2_predict=data.predict(X_test)
print("The classification report for Fish Weight is:",classification_report(Y2_test,Y2_predict))
print("The confusion matrix for Fish Weight is:",confusion_matrix(Y2_test,Y2_predict))

The classification report for Fish Length is:               precision    recall  f1-score   support

       14.64       0.00      0.00      0.00         8
       32.01       0.20      0.40      0.27         5
    32.58643       0.99      1.00      1.00       124
    39.95929       0.94      0.95      0.94       110
    40.06857       1.00      1.00      1.00        10
    40.73571       0.93      0.88      0.90        81
    41.00142       0.97      0.85      0.90        33
   41.267134       0.94      1.00      0.97       100
    41.39642       0.95      0.96      0.96       105
    41.66213       0.96      0.96      0.96       142

    accuracy                           0.94       718
   macro avg       0.79      0.80      0.79       718
weighted avg       0.94      0.94      0.94       718

The confusion matrix for Fish Length is: [[  0   8   0   0   0   0   0   0   0   0]
 [  3   2   0   0   0   0   0   0   0   0]
 [  0   0 124   0   0   0   0   0   0   0]
 [  0   0   0 104   0   4

8) Gradient Boosting Classifier

In [20]:
model=GradientBoostingClassifier()
data=model.fit(X_train,Y1_train)
Y1_predict=data.predict(X_test)
print("The classification report for Fish Length is:",classification_report(Y1_test,Y1_predict))
print("The confusion matrix for Fish Length is:",confusion_matrix(Y1_test,Y1_predict))
data=model.fit(X_train,Y2_train)
Y2_predict=data.predict(X_test)
print("The classification report for Fish Weight is:",classification_report(Y2_test,Y2_predict))
print("The confusion matrix for Fish Weight is:",confusion_matrix(Y2_test,Y2_predict))

The classification report for Fish Length is:               precision    recall  f1-score   support

       14.64       0.00      0.00      0.00         8
       32.01       0.20      0.40      0.27         5
    32.58643       0.99      1.00      1.00       124
    39.95929       0.93      0.93      0.93       110
    40.06857       1.00      0.70      0.82        10
    40.73571       0.90      0.90      0.90        81
    41.00142       0.96      0.82      0.89        33
   41.267134       0.94      0.99      0.97       100
    41.39642       0.88      0.94      0.91       105
    41.66213       0.96      0.92      0.94       142

    accuracy                           0.92       718
   macro avg       0.78      0.76      0.76       718
weighted avg       0.92      0.92      0.92       718

The confusion matrix for Fish Length is: [[  0   8   0   0   0   0   0   0   0   0]
 [  3   2   0   0   0   0   0   0   0   0]
 [  0   0 124   0   0   0   0   0   0   0]
 [  0   0   0 102   0   6

9) Naive Bayes Classifier

In [21]:
model=MultinomialNB()
data=model.fit(X_train,Y1_train)
Y1_predict=data.predict(X_test)
print("The classification report for Fish Length is:",classification_report(Y1_test,Y1_predict))
print("The confusion matrix for Fish Length is:",confusion_matrix(Y1_test,Y1_predict))
data=model.fit(X_train,Y2_train)
Y2_predict=data.predict(X_test)
print("The classification report for Fish Weight is:",classification_report(Y2_test,Y2_predict))
print("The confusion matrix for Fish Weight is:",confusion_matrix(Y2_test,Y2_predict))

The classification report for Fish Length is:               precision    recall  f1-score   support

       14.64       0.00      0.00      0.00         8
       32.01       0.38      1.00      0.56         5
    32.58643       0.00      0.00      0.00       124
    39.95929       0.11      0.11      0.11       110
    40.06857       0.00      0.00      0.00        10
    40.73571       0.00      0.00      0.00        81
    41.00142       0.00      0.00      0.00        33
   41.267134       0.00      0.00      0.00       100
    41.39642       0.00      0.00      0.00       105
    41.66213       0.21      0.89      0.34       142

    accuracy                           0.20       718
   macro avg       0.07      0.20      0.10       718
weighted avg       0.06      0.20      0.09       718

The confusion matrix for Fish Length is: [[  0   8   0   0   0   0   0   0   0   0]
 [  0   5   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0 124]
 [  0   0   0  12   0   0

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classificat